### ISSUE TITLE
Tab Character in file name

### ISSUE THREAD

**Issue by tlempicki** [davidcruy/bad-files-check#2]
First, thank you so much for creating this tool. It proved to be extremely helpful.

I had an issue in our Dropbox where the tab character was in some of our file names. I'm not really a C# developer, but it should be as easy as just adding \t to the Regex match and where it replaces the character in the fixer.

Thanks again!

**Comment by davidcruy** [comment]
Hi @tlempicki,

Currently I am missing the tab-character. I'll create a new version where I also remove \t characters.

**Comment by tlempicki** [comment]
You are a scholar and a gentleman. Thank you.

**Comment by davidcruy** [comment]
New release with support for tab character, please review:
https://github.com/davidcruy/bad-files-check/releases/tag/7

**Comment by tlempicki** [comment]
Amazing. Thank you so much!
