### ISSUE TITLE
What does the option f - fix do? 

### ISSUE THREAD

**Issue by Lod3** [davidcruy/bad-files-check#3]
Hi,  
This looks like a great solution for me thanks for this.
To be clear, does the option add an underscore instead of the illegal characters? 
I would like to fix some of these files with illegal filenames that cause sync issues. 
But I wanted to be sure of what it does exactly before I use this tool.
Merci

**Comment by davidcruy** [comment]
Hi @Lod3,

The fix option wil remove all of the invalid characters, no replacement with underscore or anything.

Kind regards!
David

**Comment by Lod3** [comment]
Hey David! 
Thanks! I hope I get it to work this tool would be such a great help.
